server:
  port: 80
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://${POSTGIS_PORT_5432_TCP_ADDR}/postgres
    username: postgres
    password: ${POSTGIS_ENV_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver