spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
    hibernate:
      ddl-auto: create-update
  datasource:
    url: jdbc:postgresql://172.17.0.1/postgres
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver